In [1]:
import numpy as np

In [2]:
np.random.seed(1)
x = np.random.uniform(-5, 5, size=(5,3))
y = np.random.uniform(0, 0, size=(5,3))
x,y

(array([[-0.82977995,  2.20324493, -4.99885625],
        [-1.97667427, -3.53244109, -4.07661405],
        [-3.13739789, -1.54439273, -1.03232526],
        [ 0.38816734, -0.80805486,  1.852195  ],
        [-2.9554775 ,  3.78117436, -4.72612407]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [ ]:
for i in range(4):
    print('iteration:', i, '----------------------------------------------')
    print('before update y:', y)
    for j in range(5):
        y[j] = y[j] + 1
        
    
    
    

In [2]:
def Y(y):
    new_y = y.copy()
    for i in range(5):
        new_y[i] = y[i] + 10
    return new_y

def X(x, y):
    new_x = x.copy()
    for i in range(5):
        new_x[i] = y[i] + x[i]
    return new_x

In [3]:
np.random.seed(1)
x = np.random.uniform(-5, 5, size=(5,3))
y = np.random.uniform(0, 0, size=(5,3))
x,y

(array([[-0.82977995,  2.20324493, -4.99885625],
        [-1.97667427, -3.53244109, -4.07661405],
        [-3.13739789, -1.54439273, -1.03232526],
        [ 0.38816734, -0.80805486,  1.852195  ],
        [-2.9554775 ,  3.78117436, -4.72612407]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [4]:

for i in range(4):
    print('iteration:', i, '----------------------------------------------')
    print('before update y:', y)
    y = Y(y)
    print('after update y:', y)
    print('before update x:', x)
    x = X(x, y)
    print('after update x:', x)
    
    

iteration: 0 ----------------------------------------------
before update y: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
after update y: [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
before update x: [[-0.82977995  2.20324493 -4.99885625]
 [-1.97667427 -3.53244109 -4.07661405]
 [-3.13739789 -1.54439273 -1.03232526]
 [ 0.38816734 -0.80805486  1.852195  ]
 [-2.9554775   3.78117436 -4.72612407]]
after update x: [[ 9.17022005 12.20324493  5.00114375]
 [ 8.02332573  6.46755891  5.92338595]
 [ 6.86260211  8.45560727  8.96767474]
 [10.38816734  9.19194514 11.852195  ]
 [ 7.0445225  13.78117436  5.27387593]]
iteration: 1 ----------------------------------------------
before update y: [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
after update y: [[20. 20. 20.]
 [20. 20. 20.]
 [20. 20. 20.]
 [20. 20. 20.]
 [20. 20. 20.]]
before update x: [[ 9.17022005 12.20324493  5.00114375]
 [ 8.02332573  6.46755891  5.92338595]
 [ 6.

In [ ]:
def f(x):
    return sum(x)

In [ ]:
np.random.seed(1)
X = np.random.uniform(-5, 5, size=(5,3))
X

In [ ]:
F = np.array([f(x) for x in X])

In [ ]:
I = np.argmin(F)
best = X[I]
fmin = F[I]
print(I, best)


In [ ]:
for i in range(5):
    print(i)
    print('best:', best, 'f:', fmin)
    x = X[i] + best
    X[i] = x
    print('X[i]:', X[i])
    F[i] = f(x)
    print('---------------------------')

In [ ]:
best

In [ ]:
import copy
def test(x):
    y = x.copy()
    for i in range(3):
        y[i] = copy.copy(x[i]) + 100
    return y

In [ ]:
l1 = [1,2,3]
l2 = test(l1)
for i in range(3):
    l1[i] = 10
    


In [ ]:
l2


In [ ]:
l1

In [ ]:
a = [1, 2, 3]
b = a
b[2] = 11

print("list a:", a)
print("list b:", b)